default:
  #cutoff value for the genes used for the Platform Effect Normalization
  gene_cutoff: .000125 #.000125
  #log fold change cutoff for the genes used for the Platform Effect Normalization
  fc_cutoff: .5
  #cutoff value for the genes used in RCTD
  gene_cutoff_reg: .0002 # .00015
  #log fold change cutoff for the genes used for the RCTD
  fc_cutoff_reg: 0.75
  #min UMI to analyze on the bead
  UMI_min: 100
  #chooseSigma epoch
  N_epoch: 8
  #number of X vals for Q mat
  N_X: 50000
  #Number of K vals in Q mat
  K_val: 100
  #N fit for chooseSigma:
  N_fit: 500
  #chooseSigma epoch for bulk
  N_epoch_bulk: 30
  #min change for bulk convergence
  MIN_CHANGE_BULK: .0001 
  UMI_max: 20000



